name: CI

on:
  push:
    branches-ignore:
      - "github-pages/*"
      - "gh-pages/*"
      - "main"
  pull_request:
    branches-ignore:
      - 'main'

jobs:

  ci-job:
    name: Checks
    uses: nicoretti/python-toolbox/.github/workflows/checks.yml@main